### ISSUE TITLE
无法访问网络

### ISSUE THREAD

**Issue by wcwq98** [RockChinQ/WebwlkrPlugin#2]
![Screenshot_20230805_125847_com tencent mobileqq](https://github.com/RockChinQ/WebwlkrPlugin/assets/85041970/5cc1c3b3-fbc3-4862-942f-ad41fe6010fe)
![Screenshot_20230805_125311_com tencent mobileqq](https://github.com/RockChinQ/WebwlkrPlugin/assets/85041970/216aba4a-a533-4180-921b-f22822ac9f25)
服务器不想挂梯子，不然上学的时候梯子容易掉，想通过把谷歌官网换成Cloud Flare搭建的谷歌镜像站来访问。

**Comment by RockChinQ** [comment]
已把搜索引擎改为搜狗，使用命令`!plugin update Webwlkr`更新插件
