### ISSUE TITLE
[Feature]: 联网插件触发时机可否更明确

### ISSUE THREAD

**Issue by zuo-shi-yun** [RockChinQ/WebwlkrPlugin#3]
### 这是一个？

现有功能优化

### 详细描述

尝试了一下联网插件，发现触发时机很不明确，有时候希望他触发，要重复好几遍才触发联网，有时候在网上搜到了结果却不使用搜索到的结果，而且网络上的答案让人觉着准确性不够高。
如果这不是openAI自己接口的问题，可否让联网插件的触发时机更明确？比如当发送"!联网搜索 xxx“时百分百去网络上搜索xxx，其余时间不通过网络搜索？
如果当使用了联网功能后再在信息里明确的表明“答案来自于网络”，也会让人对答案的准确度有更好的判断，不用担心”这个答案会不会是来自网络？准确度会不会不够高？“

**Comment by RockChinQ** [comment]
WebwlkrPlugin 允许GPT调用联网函数的机制是`内容函数`([见此wiki](https://github.com/RockChinQ/QChatGPT/wiki/%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8-%E5%86%85%E5%AE%B9%E5%87%BD%E6%95%B0) )，按照其中的标准，你可以在此仓库的`main.py`中找到此插件对联网函数的描述，通常来说，符合函数描述的情况都将触发对应的函数调用，但具体由GPT决定，这意味着我们（应用侧开发者）无法主动控制其调用。您可以尝试以下的方案获得更好的体验：

- 使用更符合函数描述的语言提问机器人
- 更换使用`gpt-4`模型
- 自行修改内容函数的描述并多次测试

## 指令要求搜索

可以自行编写插件实现

## 关于让机器人提示是否使用了函数调用

当前版本实现这个功能较为困难，预计在`3.0`版本之后可以更加灵活实现
